#!/usr/bin/env node
'use strict';

/*
 * Builds two Windows executables from the same source:
 *   dist/orbit-agent.exe       consumer build  — prompts for relay + password
 *   dist/orbit-agent-auto.exe  auto build      — relay + password baked in,
 *                                                connects on launch, no prompts
 *
 * The config is injected by rewriting baked.js before each pkg run.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const AUTO = {
  relay: 'wss://orbit-relay-c72o.onrender.com',
  token: 'Orbit123!',
  name: '',   // blank -> agent uses the machine's hostname
  root: '',   // blank -> whole machine
};
const CONSUMER = { relay: '', token: '', name: '', root: '' };

const bakedPath = path.join(__dirname, 'baked.js');

function writeBaked(cfg) {
  fs.writeFileSync(
    bakedPath,
    '// Generated by build.js — do not edit by hand.\n' +
      'module.exports = ' + JSON.stringify(cfg, null, 2) + ';\n'
  );
}

function build(output, cfg) {
  console.log(`\n=== building ${output} ===`);
  writeBaked(cfg);
  execSync(
    `npx @yao-pkg/pkg . --targets node22-win-x64 --output dist/${output}`,
    { stdio: 'inherit', cwd: __dirname }
  );
}

fs.mkdirSync(path.join(__dirname, 'dist'), { recursive: true });

try {
  build('orbit-agent.exe', CONSUMER);
  build('orbit-agent-auto.exe', AUTO);
} finally {
  // Leave the committed, empty consumer config in place.
  writeBaked(CONSUMER);
}

console.log('\nDone. See agent/dist/.');
